set(_CATKIN_CURRENT_PACKAGE "devicenode")
set(devicenode_MAINTAINER "robocare <cspark@robocare.com>")
set(devicenode_DEPRECATED "")
set(devicenode_VERSION "0.0.0")
set(devicenode_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "roscir" "geometry_msgs" "tf" "cir_msgs")
set(devicenode_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "roscir" "cir_msgs" "geometry_msgs" "tf")
set(devicenode_BUILDTOOL_DEPENDS "catkin")