set(_CATKIN_CURRENT_PACKAGE "roscir")
set(roscir_MAINTAINER "cspark <cspark@robocare.com>")
set(roscir_DEPRECATED "")
set(roscir_VERSION "0.0.0")
set(roscir_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "roslib" "cir_msgs")
set(roscir_RUN_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "roslib" "cir_msgs")
set(roscir_BUILDTOOL_DEPENDS "catkin")