#ifndef __EROBOT_DEFININITION_H__
#define __EROBOT_DEFININITION_H__

#pragma pack(push,1)

typedef struct EROBOT_COMMON_HEADER_PACKET {
	unsigned char	id;				// 1byte
	unsigned short	sub_id;			// 2byte
	unsigned char	command;		// 1byte
} EROBOT_COMMON_HEADER_PACKET;

typedef struct EROBOT_SENSOR_HEADER_PACKET {
	unsigned char	id;				// 1byte
	unsigned char	sub_id;			// 1byte
	unsigned char	command;		// 1byte
} EROBOT_SENSOR_HEADER_PACKET;

#pragma pack(pop)

#define EROBOT_COMMON_HEADER_PACKET_SIZE	4
#define EROBOT_SENSOR_HEADER_PACKET_SIZE	3
#define EROBOT_CHECKSUM_PACKET_SIZE			1
#define EROBOT_WHEEL_DATA_PACKET_SIZE		7
#define EROBOT_PANTILT_DATA_PACKET_SIZE		9
#define EROBOT_ARM_DATA_PACKET_SIZE			18
#define EROBOT_LED_DATA_PACKET_SIZE			10

/*
 *
 *		ERobot constand
 *
 */
#define EROBOT_SERIAL_BAUDRATE			115200

#define EROBOT_WHEELENCODER_DATACOUNT	3
#define EROBOT_ULTRASONIC_DATACOUNT		8
#define EROBOT_PSD_DATACOUNT			4
#define EROBOT_PANTILTXTION_DATACOUNT	3
#define EROBOT_ARM_DATACOUNT			6
#define EROBOT_TOUCH_DATACOUNT			5

#define RETURN_SUCCESS					1
#define RETURN_FAILED					-1

/*
 *
 *		Device ID
 *
 */
#define EROBOT_DEVICE_WHEEL_ID					0x03
#define EROBOT_DEVICE_WHEELENCODER_ID			0x03
#define EROBOT_DEVICE_ULTRASONIC_ID				0x05
#define EROBOT_DEVICE_PSD_ID					0x03
#define EROBOT_DEVICE_TOUCHBUTTON_ID			0x06
#define EROBOT_DEVICE_BATTERY_ID				0x06
#define EROBOT_DEVICE_PANTILT_ID				0x07
#define EROBOT_DEVICE_ARM_ID					0x08
#define EROBOT_DEVICE_LED_ID					0x06

/*
 *
 *		Device sub ID
 *
 */
#define EROBOT_DEVICE_WHEEL_SUB_ID_1			0xF3
#define EROBOT_DEVICE_WHEEL_SUB_ID_2			0xF3
#define EROBOT_DEVICE_BATTERY_SUB_ID_1			0xF6
#define EROBOT_DEVICE_BATTERY_SUB_ID_2			0xF6
#define EROBOT_DEVICE_WHEELENCODER_SUB_ID_1		0xF3
#define EROBOT_DEVICE_WHEELENCODER_SUB_ID_2		0xF3
#define EROBOT_DEVICE_ULTRASONIC_SUB_ID_1		0xF5
#define EROBOT_DEVICE_ULTRASONIC_SUB_ID_2		0xF5
#define EROBOT_DEVICE_PSD_SUB_ID_1				0xF3
#define EROBOT_DEVICE_PSD_SUB_ID_2				0xF3
#define EROBOT_DEVICE_TOUCHBUTTON_SUB_ID_1		0xF6
#define EROBOT_DEVICE_TOUCHBUTTON_SUB_ID_2		0xF6
#define EROBOT_DEVICE_PANTILT_SUB_ID_1			0xF7
#define EROBOT_DEVICE_PANTILT_SUB_ID_2			0xF7
#define EROBOT_DEVICE_ARM_SUB_ID_1				0xF8
#define EROBOT_DEVICE_ARM_SUB_ID_2				0xF8
#define EROBOT_DEVICE_LED_SUB_ID_1				0xF6
#define EROBOT_DEVICE_LED_SUB_ID_2				0xF6

/*
 *
 *		Device Command
 *
 */
#define	EROBOT_COMMAND_WHEEL_MOVE_BY_VELOCITY					0x00
#define	EROBOT_COMMAND_WHEEL_MOVE_BY_VELOCITY_XYT				0x01
#define	EROBOT_COMMAND_WHEEL_MOVE_TO_DELTA_XYT					0x02
#define	EROBOT_COMMAND_WHEEL_MOVE_BY_TR_VELOCITY				0x04
#define EROBOT_COMMAND_WHEEL_EMERGENCY_STOP						0x09
#define EROBOT_COMMAND_WHEEL_SELF_DIAGNOSIS						0x08
#define EROBOT_COMMAND_GE_VERSION								0x0F

#define EROBOT_COMMAND_WHEELENCODER_GET_ENCODER					0x0A
#define EROBOT_COMMAND_WHEELENCODER_GET_POSITION				0x0B
#define EROBOT_COMMAND_WHEELENCODER_GET_RESET					0x0C
#define EROBOT_COMMAND_WHEELENCODER_GET_DATA					0x0E

#define EROBOT_COMMAND_PSD_GET_DATA								0x0D

#define EROBOT_COMMAND_PANTILT_MOVE_TO_HOME						0x01
#define EROBOT_COMMAND_PANTILT_MOVE_TO_ABSOLUTE_POSITION		0x02
#define EROBOT_COMMAND_PANTILT_XTION_MOVE_TO_ABSOLUTE_POSITION	0x03
#define EROBOT_COMMAND_PANTILT_XTION_MOVE_TO_ABS_ALL			0x04
#define EROBOT_COMMAND_PANTILT_GET_POSITION						0x05
#define EROBOT_COMMAND_PANTILT_DETECTING_ERROR					0x0E

#define EROBOT_COMMAND_ARM_MOVE_TO_HOME							0x01
#define EROBOT_COMMAND_ARM_MOVE_LEFT_ARM						0x02
#define EROBOT_COMMAND_ARM_MOVE_RIGHT_ARM						0x03
#define EROBOT_COMMAND_ARM_MOVE_BOTH_ARM						0x04
#define EROBOT_COMMAND_ARM_GET_POSITION							0x05
#define EROBOT_COMMAND_ARM_SET_OFFSET							0x06
#define EROBOT_COMMAND_ARM_SET_HOME_POSITION					0x07
#define EROBOT_COMMAND_ARM_DETECTING_ERROR						0x0E

#define EROBOT_COMMAND_ULTRASONIC_GET_DATA						0xF5

#define EROBOT_COMMAND_TOUCHBUTTON_GET_DATA						0xF1
#define EROBOT_COMMAND_TOUCHBUTTON_DETECTING_ERROR				0x0E
#define EROBOT_COMMAND_BATTERY_GET_DATA							0xF8

/*
 *
 *		Function Factory
 *
 */
#define MAX_2BYTE_INT						32767
#define MAX_3BYTE_INT						8388607


#define RET_CHECKSUM_ERROR  -2
#define RET_NO_READ_ERROR	 -3


#define DEFAULT_SLEEP_ENCODER	100
#define DEFAULT_SLEEP_ULTRASONIC 30
#define DEFAULT_SLEEP_PSD		30
#define DEFAULT_SLEEP 10
#define DEFAULT_BUF_SIZE 36

#define EROBOT_TYPE_WHEELENCODER					0x00
#define EROBOT_TYPE_ULTRASONIC						0x01
#define EROBOT_TYPE_PSD								0x02
#define EROBOT_TYPE_TOUCHBUTTON						0x03
#define EROBOT_TYPE_WHEEL							0x04
#define EROBOT_TYPE_INTEGRATE						0x05
#define EROBOT_TYPE_ARM								0x06
#define EROBOT_TYPE_PANTILT							0x07

#endif /* __EROBOT_DEFININITION_H__ */
